spring:
  thymeleaf:
    cache: false

---
spring.profiles: dev

spring:
  datasource:
    url: jdbc:h2:mem:tempdb
    username: sa
    password:
  profiles:
    dev

logging:
  level:
    root: info

---
spring.profiles: prod
